import random
from random import randint
import turtle
import random
turtle.speed(3)
bg = turtle.Screen()
bg.bgcolor("#554c53")
turtle.pensize(5)
#tầng 1
turtle.begin_fill()
turtle.fillcolor("#e4fc13")
turtle.penup()
turtle.goto(-180, -100)
turtle.color("#e4fc13")
turtle.pendown()
turtle.forward(360)
turtle.left(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(360)
turtle.left(90)
turtle.forward(70)
turtle.end_fill()
#chu tầng 1
turtle.penup()
turtle.goto(-150, -80)
turtle.color("#361dc3")
turtle.pendown()
turtle.write("BEST WISH FOR YOU", font = ("Verdana", 21, "normal"))
#tầng 2
turtle.begin_fill()
turtle.fillcolor("#00e1ff")
turtle.penup()
turtle.goto(-140, -29)
turtle.color("#00e1ff")
turtle.pendown()
turtle.left(180)
turtle.forward(70)
turtle.right(90)
turtle.forward(280)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(280)
turtle.end_fill()
#nến
turtle.penup()
turtle.goto(-160, -29)
turtle.color("#2cc41d")
turtle.pendown()
turtle.right(90)
turtle.forward(35)
turtle.penup()
turtle.goto(-180, -3)
turtle.color("#f4f7f4")
turtle.pendown()
turtle.write("❅", font= ("Verdana", 30, "normal"))

turtle.penup()
turtle.goto(160, -29)
turtle.color("#2cc41d")
turtle.pendown()
turtle.forward(35)
turtle.penup()
turtle.goto(140, -3)
turtle.color("#f4f7f4")
turtle.pendown()
turtle.write("❅", font= ("Verdana", 30, "normal"))
#chữ tầng 2
turtle.penup()
turtle.goto(-120, -15)
turtle.color("#8a46db")
turtle.pendown()
turtle.write("BIRTHDAY", font= ("Castellar", 30, "normal"))
#tầng 3
turtle.begin_fill()
turtle.fillcolor("#f357d6")
turtle.penup()
turtle.goto(-100, 45)
turtle.color("#f357d6")
turtle.pendown()
turtle.forward(60)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(200)
turtle.end_fill()
#chữ tầng 3
turtle.penup()
turtle.goto(-75, 50 )
turtle.color("#00e1ff")
turtle.pendown()
turtle.write("HAPPY", font= ("Castellar", 30, "normal"))

turtle.penup()
turtle.goto(-147, 32)
turtle.color("#ff0000")
turtle.pendown()
turtle.write("❣️", font = ("Time New Roman", 35, "normal"))

turtle.penup()
turtle.goto(100, 32)
turtle.color("#ff0000")
turtle.pendown()
turtle.write("❣", font = ("Time New Roman", 35, "normal"))

turtle.penup()
turtle.goto(-60, 100)
turtle.pencolor("#ff4b00")
turtle.pendown()
turtle.write("... tuổi", font = ("Time New Roman", 30, "bold"))
#viết chữ BH
turtle.penup()
turtle.goto(-270, 220)
turtle.pencolor("#ff2200")
turtle.pendown()
turtle.write("HAPPY BIRTHDAY", font = ("Forte", 50))
#toD
turtle.penup()
turtle.goto(30, 150)
turtle.pencolor("#fbffb7")
turtle.pendown()
turtle.write("to ...", font = ("Jokerman", 50))

#chúc
turtle.penup()
turtle.goto(-350, -300)
turtle.pencolor("#96f5b6")
turtle.pendown()
turtle.write(".............................................................................................", font = ("VNAcial", 20))